#!/usr/bin/env bash
#sets up nginx for webserver
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo systemctl start nginx
