#!/usr/bin/env bash
#sets up nginx for webserver
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo etc/init.d/nginx restart
