#!/usr/bin/env bash
#sets up nginx for webserver
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
replace="^\tlocation / {"
new_text="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"
sudo sed -i "s@$replace@$new_text@" /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
