#!/usr/bin/env bash
#sets up nginx for webserver
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
error_loc="\terror_page 404 /error404.html;\n\n\tlocation / {"
replace="^\tlocation / {"
new_text="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"
sudo sed -i "s@$replace@$new_text@" /etc/nginx/sites-available/default
sudo sed -i "s@$replace@$error_loc@" /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
