#!/usr/bin/env bash
#indefinate loop with sleep 2 between
i=0
while ((i==0));
do
      echo "To infinity and beyond"
      sleep 2
      ((i++))
      ((i--))
      trap "{ echo 'I am invincible!!!'; }" SIGTERM
done
      
