#!/usr/bin/env bash
#printing numbers 1 to 100 with special outputs for specific number.

i=1
while ((i<101));
do
    if  ((i%3==0 && i%5==0));
    then
	echo "FizzBuzz"
    elif ((i%5==0));
    then
	echo "Buzz"
    elif ((i%3==0));
    then
	echo "Fizz"
    else
	echo $i
    fi
    ((i++))
done
