#!/usr/bin/env bash
#Testing while loops and if statements
i=1 #calling the variable
while (( i < 9 ))
do
    echo "Holberton School" &
    (( i++ ))
done

    if (( i=9 ));
       then
	   echo "Hi" &
	   (( i++ ))
    fi
    if (( i=10 ));
    then
	echo "Holberton School"
    fi
    
