#!/usr/bin/env bash
#Testing while loops and if statements
i=0 #calling the variable
while (( i < 10 ))
do
    echo "Holberton School" &
    (( i++ ))
done

    if (( i=8 ));
       then
     	   echo "Hi" &
	   (( i++ ))
    fi
