#!/usr/bin/env bash
#In this file I will be using a while loop to display every minute from hour zero to hour twelve.
j=1
i=0
while (( i < 13 ));
do
    echo "Hour: $i"

   
	
	while (( j < 60 ));
	  
	do
       	    echo "$j"
       	    (( j++ ))
	done
	(( i++ ))
	j=1
    
    
done
