#!/usr/bin/env bash
# In this file I am using if statments on files to prove existence

if [ -e holbertonschool ]
then
    echo "holbertonschool file exists"
    
    if [ -s holbertonschool ]
    then
	echo "holbertonschool file is not empty"
	if [ -f holbertonschool ]
	   then
	   echo "holbertonschool is a regular file"
	   else
	   true    
	fi
    else
	echo "holbertonschool file is empty"
	if [ -f holbertonschool ]
	   then
	   echo "holbertonschool is a regular file"
	   else
	   true    
	fi
    fi
    
else
    echo "holbertonschool file does not exist"
fi
