#!/usr/bin/env bash
# In this file I am using if statments on files to prove existence
Scho="*/holbertonschool"
if [ -e "$Scho" ]
then
    echo "$Scho file exists"
    
    if [ -s "$Scho" ]
    then
	echo "$Scho is not empty"
	if [ -f "$Scho" ]
	   then
	   echo "$Scho file is a regular file"
	   else
	   true    
	fi
    else
	echo "$Scho file is empty"
	if [ -f "$Scho" ]
	   then
	   echo "$Scho file is a regular file"
	   else
	   true    
	fi
    fi
    
else
    echo "$Scho file does not exist"
fi
