#!/usr/bin/env bash
#sets up loadbalancer for webserver
sudo apt-get update -y
sudo apt-get install haproxy -y
echo -e "frontend httpwebf\n\tmode http\n\tbind *:80\n\tdefault_backend httpwebb\nbackend httpwebb\n\tmode http\n\tbalance roundrobin\n\tserver 3612-web-01 3.91.64.93:80 check\n\tserver 3612-web-02 54.221.117.207:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLE=1" | sudo tee -a /etc/default/haproxy
sudo /etc/init.d/nginx restart
