#!/usr/bin/env bash
#setting up linux netfilter firewall with ufw
sudo apt update
sudo apt upgrade -y
sudo apt -y install ufw
sudo ufw enable
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
